# Generated by Django 4.0.1 on 2022-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='asd',
            field=models.CharField(max_length=50, null=True, verbose_name='Что-то'),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
